version: '3'
services:
  web-server:
    container_name: web
    build: ./server
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:postgres@postgres:5432
      PORT: 3000
    volumes:
      - ./server:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - pg
    links:
      - pg

  pg:
    container_name: postgres
    image: postgres:12
    volumes: 
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres